### ISSUE TITLE
Npm post-install hook should verify binary against a checksum

### ISSUE THREAD

**Issue by EricCrosson** [typescript-tools/rust-implementation#102]
During the semantic-release process, we should checksum each binary and embed this in the npm package that functions as a post-install hook. The binary downloaded from the GitHub release can be verified at download time against the checksum calculated inside GitHub actions

Also can publish the checksums in the GitHub release

**Comment by ericcrosson-bitgo** [comment]
Splitting this into two issues, one to add the checksum and the other to use it from the postinstall hook

**Comment by EricCrosson** [comment]
Completed
