### ISSUE TITLE
Discrepancy between `monorepo --version` and npm version

### ISSUE THREAD

**Issue by ericcrosson-bitgo** [typescript-tools/rust-implementation#124]
To my knowledge this hasn't happened in a published version yet, but here is a CI build where the version calculated by standard-version is 4.0.1, while semantic release calculated 4.0.0.

The risk afforded by this issue is we publish an npm package X, that installs a monorepo binary that proclaims version Y. This would be confusing to the end user.

The reason we calculate the next semantic version manually (outside of semantic release) is because semantic-release does not provide a way to output the next version, which we need at compile time to embed in each Rust binary. We also want to build the binaries in parallel and on different machines, so we cannot perform all the compilation inside a single semantic-release invocation. Related issue: https://github.com/semantic-release/semantic-release/issues/753

[logs_309.zip](https://github.com/typescript-tools/rust-implementation/files/8372893/logs_309.zip)

**Comment by EricCrosson** [comment]
npm is no longer used as a distribution channel
